import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ArrowLeft, Download, Loader2, Play, Sparkles, Send, RefreshCcw } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { Link, useLocation } from "wouter";
import { Streamdown } from "streamdown";

const order = ["business", "audit", "problems", "opportunities", "strategy", "brand", "sitemap", "design_system", "pages", "content", "design_brief", "stitch_prompts", "build_spec"];
const labels: Record<string, string> = { business: "Business", audit: "Audit", problems: "Problems", opportunities: "Opportunities", strategy: "Strategy", brand: "Brand DNA", sitemap: "Sitemap", design_system: "Design System", pages: "Pages", content: "Content", design_brief: "Design Brief", stitch_prompts: "Stitch Prompts", build_spec: "Handoff" };

export default function PipelineDetail({ auditId }: { auditId: string }) {
  const [, setLocation] = useLocation();
  const utils = trpc.useUtils();
  const detail = trpc.pipeline.detail.useQuery({ auditId });
  const [activeType, setActiveType] = useState<string>(() => new URLSearchParams(window.location.search).get("artifact") ?? "audit");
  const [exportFormat, setExportFormat] = useState<"json" | "markdown" | "pdf">("pdf");
  const regenerate = trpc.pipeline.regenerateDemoArtifact.useMutation({ onSuccess: async () => { await utils.pipeline.detail.invalidate({ auditId }); toast.success("New DEMO version created"); }, onError: e => toast.error(e.message) });
  const llm = trpc.pipeline.improveWithLlm.useMutation({ onSuccess: async () => { await utils.pipeline.detail.invalidate({ auditId }); toast.success("LLM enhancement saved", { description: "This version is labeled as AI inference." }); }, onError: e => toast.error("LLM enhancement unavailable", { description: e.message }) });
  const handoff = trpc.pipeline.prepareResultHandoff.useMutation({ onSuccess: result => toast.success("Outbound handoff prepared", { description: result.note }), onError: e => toast.error(e.message) });
  const exportArtifact = trpc.pipeline.exportArtifact.useMutation({ onSuccess: file => { window.open(file.storageUrl, "_blank", "noopener,noreferrer"); toast.success("Export stored in S3", { description: file.fileName }); }, onError: e => toast.error("Export unavailable", { description: e.message }) });
  const current = useMemo(() => {
    if (!detail.data) return undefined;
    return detail.data.artifacts.find(item => item.artifactType === activeType) ?? detail.data.artifacts[0];
  }, [activeType, detail.data]);
  if (detail.isLoading) return <div className="min-h-screen grid place-items-center bg-[#f7f3ed]"><Loader2 className="animate-spin text-[#c86145]" /></div>;
  if (!detail.data) return <div className="min-h-screen grid place-items-center bg-[#f7f3ed] text-[#18344a]">Pipeline not found.</div>;
  const { audit, business, stages, artifacts } = detail.data;
  const stageMap = new Map(stages.map(stage => [stage.stage, stage]));
  const artifactTypes = Array.from(new Set(artifacts.map(item => item.artifactType)));
  return <main className="min-h-screen bg-[#f7f3ed] text-[#18344a]"><header className="border-b border-[#d8d0c4] bg-[#f7f3ed] px-5 py-4 sm:px-8"><div className="mx-auto flex max-w-[1600px] items-center justify-between"><Link href="/" className="inline-flex items-center gap-2 font-mono text-xs uppercase tracking-[.13em] text-[#61706f] hover:text-[#c86145]"><ArrowLeft className="h-4 w-4" /> Dashboard</Link><Badge className="rounded-full bg-[#dfeeea] text-[#246052] hover:bg-[#dfeeea]">Pipeline complete</Badge></div></header>
    <div className="mx-auto max-w-[1600px] p-5 sm:p-8"><section className="flex flex-col justify-between gap-5 border-b border-[#d8d0c4] pb-7 lg:flex-row lg:items-end"><div><p className="font-mono text-xs uppercase tracking-[.16em] text-[#c86145]">{audit.auditId} · {business.dataOrigin.replace("_", " ")}</p><h1 className="mt-3 font-[Fraunces] text-5xl leading-none sm:text-6xl">{business.name}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#61706f]">{business.category ?? "Business"} · {business.location ?? "Location not supplied"} · audit score <strong>{audit.overallScore ?? 0}/100</strong></p></div><div className="flex flex-wrap items-center gap-2"><Button variant="outline" onClick={() => handoff.mutate({ auditId })} disabled={handoff.isPending} className="rounded-full border-[#18344a] text-[#18344a]"><Send className="mr-2 h-4 w-4" /> Prepare handoff</Button><select aria-label="Export format" value={exportFormat} onChange={event => setExportFormat(event.target.value as "json" | "markdown" | "pdf")} className="h-9 rounded-full border border-[#d8d0c4] bg-white px-3 text-xs text-[#18344a]"><option value="pdf">PDF</option><option value="json">JSON</option><option value="markdown">Markdown</option></select><Button onClick={() => { if (["design_system", "content", "build_specification"].includes(current?.artifactType ?? "")) exportArtifact.mutate({ auditId, artifactType: current!.artifactType as "design_system" | "content" | "build_specification", format: exportFormat }); else toast.info("Choose an exportable artifact", { description: "Exports are available for Design System, Content and Build Specification." }); }} disabled={exportArtifact.isPending} className="rounded-full bg-[#18344a] text-white hover:bg-[#294c64]"><Download className="mr-2 h-4 w-4" /> Export</Button></div></section>
      <section className="mt-6 overflow-x-auto"><div className="flex min-w-max items-center gap-0">{order.map((key, index) => { const stage = stageMap.get(key as any); return <div className="flex items-center" key={key}><button onClick={() => { const found = Object.entries({ audit: "audit", problems: "problems", opportunities: "opportunities", strategy: "strategy", brand: "brand_dna", sitemap: "sitemap", design_system: "design_system", pages: "page_specifications", content: "content", design_brief: "design_brief", stitch_prompts: "stitch_prompts", build_spec: "build_specification" }).find(([stageKey]) => stageKey === key); if (found) setActiveType(found[1]); }} className={`grid h-9 min-w-9 place-items-center rounded-full border text-xs font-semibold ${stage?.status === "ready" ? "border-[#2f6c5e] bg-[#2f6c5e] text-white" : "border-[#d8d0c4] text-[#a0aaa6]"}`}>{index + 1}</button>{index < order.length - 1 && <div className={`h-px w-4 ${stage?.status === "ready" ? "bg-[#2f6c5e]" : "bg-[#d8d0c4]"}`} />}</div>; })}</div><div className="mt-3 flex min-w-max gap-4">{order.map(key => <span className="w-[29px] text-center font-mono text-[8px] uppercase tracking-tight text-[#71807c]" key={key}>{labels[key]}</span>)}</div></section>
      <section className="mt-6 grid gap-6 xl:grid-cols-[240px_minmax(0,1fr)]"><aside className="rounded-[1.5rem] bg-[#18344a] p-3 text-[#f7f3ed]"><p className="px-3 pb-3 pt-2 font-mono text-[10px] uppercase tracking-[.17em] text-[#e9b8a4]">Artifacts</p>{artifactTypes.map(type => <button onClick={() => setActiveType(type)} key={type} className={`mb-1 flex w-full items-center justify-between rounded-xl px-3 py-3 text-left text-sm ${current?.artifactType === type ? "bg-white/12" : "text-[#d6e0e4] hover:bg-white/8"}`}><span>{type.replaceAll("_", " ")}</span><span className="font-mono text-[10px] text-[#e9b8a4]">v{artifacts.find(item => item.artifactType === type)?.version}</span></button>)}</aside>
        <article className="min-w-0 rounded-[1.5rem] border border-[#d8d0c4] bg-white p-5 sm:p-8">{current ? <><div className="flex flex-col justify-between gap-4 border-b border-[#ece6dd] pb-5 md:flex-row md:items-start"><div><div className="flex flex-wrap items-center gap-2"><Badge variant="outline" className="border-[#d8d0c4] font-mono text-[10px] uppercase">{current.provider}</Badge><Badge className={`font-mono text-[10px] ${current.dataOrigin === "ai_inference" ? "bg-[#fbe8a7] text-[#735a00] hover:bg-[#fbe8a7]" : "bg-[#e7edf0] text-[#3f5661] hover:bg-[#e7edf0]"}`}>{current.dataOrigin.replace("_", " ")}</Badge></div><h2 className="mt-4 font-[Fraunces] text-4xl leading-none">{current.title}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#61706f]">{current.summary}</p></div><div className="flex shrink-0 gap-2"><Button size="sm" variant="outline" onClick={() => regenerate.mutate({ auditId, artifactType: current.artifactType as any })} disabled={regenerate.isPending} className="rounded-full border-[#d8d0c4]"><RefreshCcw className="mr-1.5 h-3.5 w-3.5" /> DEMO</Button><Button size="sm" onClick={() => llm.mutate({ auditId, artifactType: current.artifactType as any })} disabled={llm.isPending} className="rounded-full bg-[#c86145] text-white hover:bg-[#b95036]"><Sparkles className="mr-1.5 h-3.5 w-3.5" /> Improve with LLM</Button></div></div><ArtifactView artifact={current} /></> : <div>Artifact not found.</div>}</article></section>
    </div></main>;
}

function ArtifactView({ artifact }: { artifact: { artifactType: string; payload: Record<string, unknown> } }) {
  const payload = artifact.payload; const markdown = payload.generatedMarkdown;
  if (typeof markdown === "string") return <div className="prose prose-slate mt-7 max-w-none"><Streamdown>{markdown}</Streamdown></div>;
  if (artifact.artifactType === "design_system") { const colors = payload.colors as Record<string, string> | undefined; return <div className="mt-8"><p className="font-mono text-xs uppercase tracking-[.15em] text-[#71807c]">Proposed visual tokens</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{Object.entries(colors ?? {}).map(([name, color]) => <div className="rounded-2xl border border-[#ece6dd] p-3" key={name}><div className="h-20 rounded-xl" style={{ background: String(color) }}/><p className="mt-3 text-sm font-semibold capitalize">{name}</p><p className="font-mono text-xs text-[#71807c]">{String(color)}</p></div>)}</div><div className="mt-6 rounded-xl bg-[#f7f3ed] p-4 text-sm leading-6 text-[#61706f]">This proposed system is a starting direction. It is not an official brand system until validated with the business.</div></div>; }
  const items = payload.items as Array<Record<string, unknown>> | undefined; const pages = payload.pages as Array<Record<string, unknown>> | undefined;
  if (items) return <div className="mt-7 grid gap-3">{items.map((item, index) => <div className="rounded-2xl border border-[#ece6dd] p-4" key={index}><div className="flex items-center justify-between gap-3"><p className="font-semibold">{String(item.description ?? item.type ?? `Item ${index + 1}`)}</p>{Boolean(item.severity) && <Badge className="rounded-full bg-[#fbe8e3] text-[#9b3d29] hover:bg-[#fbe8e3]">{String(item.severity)}</Badge>}</div><p className="mt-2 text-sm leading-6 text-[#61706f]">{String(item.recommendation ?? item.businessValue ?? item.evidence ?? "")}</p></div>)}</div>;
  if (pages) return <div className="mt-7 grid gap-3 md:grid-cols-2">{pages.map((page, index) => <div className="rounded-2xl border border-[#ece6dd] p-4" key={index}><p className="font-[Fraunces] text-2xl">{String(page.pageName ?? page.page ?? `Page ${index + 1}`)}</p><p className="mt-2 text-sm leading-6 text-[#61706f]">{String(page.purpose ?? "")}</p><p className="mt-4 font-mono text-[10px] uppercase tracking-[.12em] text-[#c86145]">CTA · {String(page.primaryCta ?? "to be defined")}</p></div>)}</div>;
  return <pre className="mt-7 overflow-x-auto rounded-2xl bg-[#18344a] p-5 text-xs leading-6 text-[#d6e0e4]">{JSON.stringify(payload, null, 2)}</pre>;
}
